@extends('layouts.main')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="py-5 mt-5">
                <h2>{{$title}}</h2>

                <p>The terms & conditions below apply to your use of the following website owned and operated by Event.ZAS (“Event.ZAS”): www.eventzas.com. These terms & conditions also apply to the various services, including all information, communications, links, software, e-newsletters, products, services, other materials and any and all other services that may be added, offered or provided to you from time to time (the “Services”) through these sites (collectively the “Site” which shall include the Services).</p>

                <p>By using, browsing/viewing part or all of the pages on the Site, you agree to be immediately bound by the Terms of Use set forth below. If you do not agree to these Terms of Use, do not use the Site. Event.ZAS reserves the right to change the Terms of Use at any time, at its sole discretion, without giving any prior notice. Any and all modified Terms of Use shall be effective immediately once they are posted. Event.ZAS encourages you as well as other users to periodically review this page, because any and all changes will automatically be binding on you. This Agreement may not be modified, edited, and/or changed by you in any manner.</p>

                <h3>1. EVENT.ZAS IS A NEUTRAL PARTY</h3>
                
                <p>The Site is an innovative platform and marketplace for event vendors. The Site is not a product, and Event.ZAS is not a service provider, event vendor, agent or vendor representative. Visitors of the Site, hereafter referred to as "Visitors", include and companies and other third parties offering products and services related to event ("Vendors"). Event.ZAS, its partners and subsidiaries and the Site function solely as a neutral party and marketplace where Visitors and Vendors can and may connect for a particular type of service or product. Event.ZAS is not involved, nor is Event.ZAS a party to the actual transaction between users. Therefore, Event.ZAS has no control over the quality, accuracy, safety, or legality of transactions on the Site. Nor does Event.ZAS have any control over accuracy of listings, vendor pages, or the ability of Vendors to provide the items or services they promote. Event.ZAS is not responsible for the actions or failures of Visitors or Vendors.</p>
                
                <p>Visitor: By agreeing to these Terms of Use, you acknowledge the following: Event.ZAS does not provide or guarantee any products or services advertised and/or offered by Vendors. Event.ZAS does not endorse any Vendor on the Site, nor does Event.ZAS guarantee the quality of any Vendor goods or services. Any and all communications, correspondence, verbal or non-verbal between Visitors and Vendors, or any warranties or representations by Vendors are between you and the Vendor. No products or services offered on the Site, are actually offered/provided by Event.ZAS, they are solely between you and the Vendor. Therefore any transactions between you and a Vendor are strictly between you and that Vendor. Event.ZAS is not, nor will it ever be a party to that transaction. You agree hereby that any dispute between you and a Vendor is solely between you and that Vendor, and not Event.ZAS. Furthermore, Event.ZAS cannot guarantee nor does Event.ZAS warrant that information provided by or about Vendors on the Site is accurate.</p>
                
                <p>Vendors: Any and all transactions between you and Visitors are strictly between you and the Visitors, whereby you as a Vendor agree that Event.ZAS is not a party to that transaction. Therefore, you also agree that any dispute with a Visitor is solely between you and the Visitor, whereby Event.ZAS will not be a party to that dispute. After we, Event.ZAS and you terminate our relationship, you agree unconditionally that Event.ZAS is entitled to retain all reviews associated with your account on the Site. Furthermore you also agree that Event.ZAS shall have the right to retain and update basic directory information about your business or personal account, including, without limitation or restriction, business name(s), address(es) and telephone number(s).</p>
                
                <h3>2. FREE TRIAL</h3>
                
                <p>"Free Trial," or any other form of unpaid Vendor Account(s) may from time to time be offered by Event.ZAS. These Free Trials or unpaid Vendor Account(s) do not guarantee any advertising placements, page views, potential lead, or any other kinds of benefits. Event.ZAS reserves the right and you agree that Event.ZAS has the right at its sole discretion to modify at any time these Terms of Use or cancel any Free/Unpaid Vendor Account(s).</p>
                
                <h3>3. PROHIBITED ACTIVITIES</h3>
                
                <p>Visitors and Vendors must NEVER create an account in another Visitor/non-visitor or Vendor’s name; must not create more than one account or use the account of another Visitor or Vendor. Visitors and Vendors must NEVER impersonate another Visitor/non-visitor or Vendor. Furthermore it is strictly prohibited to use information on the Site to send unsolicited email(s) or do anything that interferes with the Site (as determined by Event.ZAS in its sole discretion). You understand and agree to refrain from all these prohibited activities and agree not to use the Site if your membership has been temporarily or permanently suspended or revoked. Finally you agree not to violate any of the terms set forth in these Terms of Use.</p>
                
                <h3>4. INTELLECTUAL PROPERTY (IP)</h3>
                
                <p>The Site contains and uses copyrighted material, inventions, know how, patented and non-patented business material, phrases and descriptions, reviews, names, logos, HTML/C++ codes and/or other computer code/scripts (collectively, "Intellectual Property Content"), all of which you agree are the sole property of Event.ZAS. By using the Site, you also agree that Event.ZAS has the right to claim ownership under all international and local copyright and trademark laws, what concerns the "look", "feel", "appearance" and "graphic function" of the Site. You agree that this right includes, but is not limited to the Site’s color combinations, user experience, sounds, layouts and designs. Furthermore, by using the Site, you agree and acknowledge that you do not have any license or permission to use the Intellectual Property (IP) of Event.ZAS. You promise not to reproduce, modify, display, sell, or distribute the Intellectual Property listed on the Site, including but not limited to information contributed by you or any other Visitors/non-visitors/Wedding Visitors or Vendors. You may not, and you agree not to frame or link to/create backlinks to the Site without the explicit prior written permission of Event.ZAS . You shall not contest our right of title to or license at any time. You shall not use or ever register any domain name or trademark that is identical or similar to any that is owned by Event.ZAS.</p>
                
                <h3>5. DISPUTES AMONG USERS</h3>
                
                <p>You are solely responsible for your interactions with other users of the Site, and you agree that Event.ZAS is not a party to any such disputes. Furthermore, you agree to fully release the Site, Event.ZAS, its officers, directors, shareholders, partners, affiliates, agents and employees from any and all potential, current and future claims, demands and damages.</p>
                
                <h3>6. PERSONAL DATA</h3>
                
                <p>If you submit or provide any personal data through the Site, your personal data will be collected, used, disclosed and/or processed by Event.ZAS for the following purposes:</p>

                <ol type="a">
                    <li>For registered members,your name and email address will be disclosed to the relevant Vendors when you click on any contact details the Vendors display in their profiles including website, email, social media (e.g. facebook, twitter, instagram), phone number, and other contacts.</li>
                    <li>To send you notices, information, promotions and updates including marketing and advertising materials in relation to our Site and services and those of third party organizations selected by Event.ZAS.</li>
                    <li>For Event.ZAS or its designated representatives or business partners to provide goods and services to you or parties designated by you and matters ancillary thereto.</li>
                    <li>To verify and process payment when you purchase goods and services from Event.ZAS.</li>
                    <li>For verification and record of your personal particulars including comparing it with information from other sources and using the information to communicate with you.</li>
                    <li>To conduct statistical analysis of the users of the Site including the number of users, the frequency of use, profile of users and using such analysis for our business plans, the enhancement of our products and services, targeted advertisements and conveying such information in broad terms (but not information in relation to specific individuals) to third parties who have or propose to have business dealings with us.</li>
                    <li>To comply with any request from any third party or any order of court or directive from authorities investigating any alleged offence or misconduct or for the purposes of taking legal action against any users. By accepting these Terms of Use, you: (a) consent to Event.ZAS collecting, using, disclosing and/or processing your personal data for the purposes as described above; (b) consent to Event.ZAS Singapore transferring your personal data out of Singapore to third party service providers or agents for the purposes as described above. If you have any questions relating to Event.ZAS Singapore’s collection, use and disclosure of your personal data, please contact support@eventzas.com.</li>
                </ol>
                
                <h3>7. INFORMATION AND OTHER CONTRIBUTIONS YOU SUBMIT TO THE SITE</h3>
                
                <p>When you post or submit information and any other contributions (including but not limited to any text, graphics, video and/or audio content, other materials or information) (collectively “Submitted Contributions”) to any part of the Site, you automatically grant, represent and warrant that you have the right/ownership to give to Event.ZAS a transferable, royalty-free, worldwide license to use, duplicate and distribute such Submitted Contributions for any purpose and in any format on or in connection with the Site or the promotion thereof. You also grant Event.ZAS permission to, at its sole discretion, grant and authorize sublicenses of all of the foregoing to itself or other third parties. You agree and acknowledge that Event.ZAS may retain copies of your Submitted Contributions and may continue to use your Submitted Contributions however Event.ZAS pleases. Furthermore, by posting Submitted Contributions, you expressly represent and warrant the following: (i) you are the owner, with all rights, of any and all content and/or information that you post on the Site; or (ii) you are the legitimate and rightful owner of a worldwide, royalty free, sub-licensable, non-exclusive license for communication, content and/or information, which you can use, distribute and reproduce. You furthermore testify and warrant that all persons and entities connected with your Submitted Contributions, and all other persons and entities whose names, voices, photographs, likenesses, works, services and materials have been used in the Submitted Contributions, have given you authorization for the use of their names, voices, photographs, likenesses, performances, and other data in connection with the advertising, promotion, trade and other exploitation of the Submitted Contributions and that all rights granted therein you hereby transfer to Event.ZAS. You agree that your Submitted Contributions does not, nor will it ever violate, or possibly cause Event.ZAS to violate any laws or regulations; will not violate these Terms of Use; will not infringe any intellectual property rights including but not limited to copyright, patent or trademark rights. You understand and agree that Event.ZAS strictly prohibits the posting of any obscene, lewd, or suggestive content/pornography. You agree and warrant that the information you post is not, nor will it ever be interpreted as libelous, threatening, harassing, racist, religious or defamatory and that the information you post will not be to advertise products or services of others or competitors of Event.ZAS, and that it will never contain any links to third-party web sites. You agree and promise that the information you post does not contain proprietary information of another person or entity; and that if it does, you will notify Event.ZAS immediately but that it will not nor will it ever create any liability of any sort for Event.ZAS in any manner whatsoever.</p>
                
                <h3>8. RATING AND REVIEW DISPUTES</h3>
                
                <p>If you undermine the integrity of the Event.ZAS Rating and Review system in any way, your account will immediately be suspended or terminated.</p>
                
                <h3>9. MANIPULATING RATINGS AND REVIEWS</h3>
                
                <p>You acknowledge and agree that you have not, do not intend to, or will you ever offer anyone cash or other compensation for a more favorable review. You furthermore agree to never misrepresent or impersonate another Vendor or Visitor. As a Vendor you agree to never post any fake feedback reviews of your own service, or attempt to gain multiple feedbacks from the same Visitor pretending to be a different Visitor. You understand and agree that reviews posted on the Site are property of Event.ZAS and are therefore protected by the IP rights as listed above. You agree that you will never copy and paste, partially or whole, any reviews from Visitors anywhere on the Site, onto your own personal, business website or any other website or platform.</p>
                
                <h3>10. NO AGENCY</h3>
                
                <p>You hereby agree and acknowledge that you do not have any contractor (independent or other), agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship, or other with Event.ZAS. You furthermore agree that no affiliation, association or connection exists between you and Event.ZAS. You shall never have any authority to bind, commit, contract for, or otherwise obligate Event.ZAS in any manner whatsoever.</p>

                <h3>11. RIGHT TO REJECT OR REMOVE MEMBERS</h3>

                <p>Event.ZAS reserves the absolute right to reject your participation, or remove you from your current participation, in the Site at any time and for any reason without notice to you.</p>

                <h3>12. CONFIDENTIALITY/NON-DISCLOSURE</h3>

                <p>Event.ZAS may disclose to you or you may learn of our documents, technical (such as but not limited to object code, source code, software), financial and operating information of Event.ZAS, graphical, business information or practices, management styles, day-to-day business operations, capabilities, systems, marketing information, technologies, processes, procedures, methods and applications, or otherwise, whether tangible or intangible, concerning or regarding Event.ZAS or the Site, including but not limited to all forward looking plans and strategies whether they be current or future, business plans, business concepts, website designs and layouts, all information, data, intellectual property and other opinions, forecasts (collectively “Event.ZAS Information”). You hereby agree and acknowledge that any and all of Event.ZAS  Information is confidential and shall be the sole and exclusive intellectual property and proprietary information of Event.ZAS, whether the information is in oral, visual or written from or is recorded in any other medium. Disclosure of any or all Event.ZAS  Information to anyone, especially a direct competitor is strictly prohibited. You acknowledge and agree that Event.ZAS shall be entitled to monetary damages and that Event.ZAS shall be entitled to injunctive relief if you fail to adhere to these agreements.</p>

                <h3>13. RECORD KEEPING/AUDIT</h3>

                <p>Event.ZAS reserves the right to keep all records of any and all communications between you and other users.</p>

                <h3>14. LIMITED LIABILITY</h3>

                <p>IN NO EVENT SHALL EVENT.ZAS, ITS AFFILIATES, ITS PARTNERS OR SUBSIDIARES, OUR EMPLOYEES, DIRECTORS, SHAREHOLDERS OR INVESTORS BE LIABLE FOR ANY DIRECT OR INDIRECT DAMAGES, LOSSES, OR DAMAGES OF ANY KIND WHATSOEVER ARISING OUT OF OR RELATING TO THE USE OF THE SITE OR FOR ANY DECISION AND ACTION MADE BY YOU IN RELIANCE ON INFORMATION CONTAINED ON THE SITE. ANY POSSIBLE LIABILITY, BY EVENT.ZAS, ITS PARTNERS OR SUBSIDIARES, OUR EMPLOYEES, DIRECTORS, SHAREHOLDERS OR INVESTORS, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO ONE QUARTER (1/4th) OF THE AMOUNT OF FEES YOU PAY TO EVENT.ZAS IN THE 12 MONTHS PRIOR. EVENT.ZAS, ITS AFFILIATES, ITS PARTNERS OR SUBSIDIARES, OUR EMPLOYEES, DIRECTORS, SHAREHOLDERS OR INVESTORS PROVIDE THE SITE AND THE SERVICES THEREON "AS IS" WITHOUT ANY WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY.</p>

                <h3>15. DO NOT HOLD LIABLE</h3>

                <p>You agree not to hold Event.ZAS, its affiliates, its partners or subsidiaries, our employees, shareholders or investors liable from any claim or demand, made by anyone or any entity, due to your use of the Site. In no event shall Event.ZAS Singapore or any of its affiliates, partners, subsidiaries, employees, shareholders or investors be liable for any loss, injury, damage, claims, costs or expense of any kind arising from any error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus or other harmful elements, communication line failure, breach of contract, tort, negligence, defamation, copyright infringement, breach of intellectual property right or any other cause of action.</p>

                <h3>16. INDEMNITY</h3>

                <p>You agree to defend and hold Event.ZAS, its affiliates and related corporations from and against all claims, losses, damages, costs and expenses, including legal fees on an indemnity basis, arising out of your use of the Site or any breach of these terms. You agree that this includes but is not limited to (i) your advertising, providing or failure to provide or pay for goods or services promoted on the Site; and (ii) any potential claims that any part or all of your Submitted Contributions includes copyrighted or non-copyrighted materials owned by third parties without authorization, or that what you posted was defamatory or harassing, or that it otherwise violated the rights of any person or any entity. In addition, Event.ZAS may use whatever information that is available about you to stop any such breach or any unlawful or inappropriate use of the Site, including informing any third party Event.ZAS deems appropriate of such breach or use and/or disclosing your personal information to such third party.</p>

                <h3>17. LINKS TO OTHER SITES</h3>

                <p>This Site may contain links to other sites which are provided solely as a convenience to you, or which are provided by other users. Event.ZAS is not responsible for the availability of external sites or resources linked to the Site, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. Transactions that occur between you and such third-party sites are strictly between you and the third party and are not the responsibility of Event.ZAS . Because Event.ZAS is not responsible for the availability or accuracy of these outside resources or their contents, you should review the terms and conditions and privacy policies of these linked sites, as their policies may differ from ours.</p>

                <h3>18. GOVERNING LAW</h3>

                <p>You agree that the laws of the Republic of Singapore will govern these Terms of Use. Any dispute arising out of the use of the Site shall be referred to the Singapore courts and you irrevocably submit to the jurisdiction of the Singapore courts.</p>

                <h3>19. NOTICE</h3>

                <p>You hereby agree and acknowledge: (a) that all electronic communications made pursuant to the use of this Site shall be given legal effect, validity and enforceability and shall have, between the parties thereto, comparable evidential value to that accorded to a signed written document; (b) not to contest the legally binding nature, validity or enforceability of any transaction on the Site on the ground that it was entered into electronically.</p>
                
                <p>Version 1.0 - Effective date: January 1, 2017.</p>
            </div> 
        </div>
    </div>
</div>
@endsection